export const UI_COPY = {
  app: {
    eyebrow: 'AD&D',
    title: 'AD&D Idle Prototype',
    lede:
      'Three-band Crystal staffing, brownouts, field budget, early base projects, and full offline catch-up now form the real first idle loop.',
    gameView: 'Game View',
    adminView: 'Admin View',
    dataTreeView: 'Data Tree',
    runtime: 'Runtime',
    crystal: 'Crystal',
    bubble: 'Bubble',
  },
  common: {
    source: 'Source',
    sink: 'Sink',
    risk: 'Risk',
    blocker: 'Blocker',
    ready: 'Ready',
    loading: 'Loading',
    noDirectAction: 'No direct action',
    unavailable: 'Unavailable',
    locked: 'Locked',
    stable: 'Stable',
    off: 'Off',
    on: 'On',
    dismiss: 'Dismiss',
    noSource: 'No source',
    noSink: 'No active sink',
    noBlocker: 'No active blocker',
    noBuilders: 'No builders assigned',
    noProject: 'No active project',
    noBaseSink: 'No active base sink',
    noBaseSource: 'No active base source',
    noBandSource: 'No active band source',
    noGrowth: 'No growth',
    noWorldAction: 'No world action',
    heroAvailable: 'Hero available',
    notBuilt: 'Not Built',
    powered: 'Powered',
    brownout: 'Brownout',
    standby: 'Standby',
    offlineCatchupDisabled: 'Offline catch-up does not progress this action.',
    noResourceCost: 'No resource cost',
    timeOnly: 'time only',
    stoneCommitted: 'Stone committed',
    basslineConsumed: 'Bassline consumed',
    costsCommitted: 'Costs committed',
    inProgress: 'In Progress',
    readyNow: 'Ready now',
    blocked: 'Blocked',
    open: 'Open',
    booting: 'Booting',
    waitingState: 'Waiting for simulation state.',
    runtimeNotReady: 'Runtime not ready',
    initialGameState: 'Initial game state',
    assignConstructionCrew: 'Assign Construction Crew',
    projectPausedNoBuilders: 'Project paused: no builders',
    projectPausedNeedBassline: 'Project paused: need Bassline',
    powerStable: 'Power stable',
    housingStable: 'Housing Stable',
    availableNow: 'Available',
    online: 'Online',
    needsPower: 'Needs Power',
    heroBuilding: 'Hero building',
    prepBase: 'Prep Base',
    restored: 'Restored',
    built: 'Built',
    constructionRunning: 'Construction is already running.',
    currentProject: 'current project',
  },
  hero: {
    kicker: 'Hero',
    name: 'The Hero',
    task: 'Task',
    status: 'Status',
    active: 'Active',
    idle: 'Idle',
    available: 'Available',
    busyWorldAction: 'Busy on world action',
    assigned: 'Assigned',
    xpSuffix: 'XP',
    levelPrefix: 'Lv',
    classes: {
      drummer: 'Drummer',
      vocalist: 'Vocalist',
      synth: 'Synth',
    },
  },
  crystal: {
    kicker: 'Crystal Circle',
    freeSlots: 'Free Slots',
    bands: {
      bassline: 'Bassline',
      chorus: 'Chorus',
      harmonics: 'Harmonics',
    },
    output: 'Output',
    fieldPolish: 'Field Polish',
    bubbleBudget: 'Bubble Budget',
    rate: 'Rate',
    stations: 'Stations',
    lifeSupport: 'Life Support',
    tier: 'Tier',
    boost: 'Boost',
    noActiveSink: 'No active sink',
    safeBuffer: (value: number) => `Safe buffer ${value.toFixed(1)}`,
    belowSafeBudget: 'Below safe budget',
    spendCarefully: 'Spend carefully',
    crew: 'Crew',
    hero: 'Hero',
    moss: 'Moss',
    building: 'Building',
    bubbleRisk: 'Bubble risk',
    powerStable: 'Power stable',
    tierDormant: '0 · Dormant',
    tierSoundcheck: '1 · Soundcheck',
    tierRehearsal: '2 · Rehearsal',
    tierLiveSet: '3 · Live Set',
    heroAssignedTo: (title: string) => `Hero assigned to ${title}`,
  },
  map: {
    kicker: 'Map',
    caveGateOpen: 'Cave Gate Open',
    reachLabel: 'Reach',
    frontierLabel: 'Frontier',
    targetLabel: 'Target',
    caveGateInLabel: 'Cave Gate in',
    shrinkWarningLabel: 'Bubble will shrink in',
    reach: (value: number) => `Reach ${value}`,
    frontier: (value: number) => `Frontier ${value}%`,
    target: (ring: number, progress: number) => `Target R${ring} ${progress}%`,
    caveGateIn: (reach: number) => `Cave Gate in ${reach} reach`,
    bubbleWillShrinkIn: (seconds: number) => `Bubble will shrink in: ${seconds.toFixed(1)}s`,
  },
  narrative: {
    kicker: 'Introduction',
    title: 'Arrival',
    choiceLabel: 'Choose your line',
    selectedLabel: 'Chosen',
    unlockLabel: 'This sets up',
    continueLabel: 'Continue',
    actionReady: 'Ready to act',
  },
  objectives: {
    kicker: 'Objectives',
    title: 'First Session Path',
    current: 'Current',
    activeGoal: 'Active Goal',
    afterThat: 'After That',
    blockingThis: 'Blocking This',
    thisUnlocks: 'This Unlocks',
    doThisNext: 'Do This Next',
    watchOut: 'Watch Out',
    noDirectAction: 'No direct action',
    loadingTitle: 'Loading',
    loadingSummary: 'Waiting for simulation state.',
    investigateBase: 'Investigate Base',
    exploreBase: 'Explore Base',
    restoreStudio: 'Restore Studio',
    buildFirePit: 'Build Fire Pit',
    reachSurvivorCave: 'Reach Survivor Cave',
    recruitFirstSurvivor: 'Recruit First Survivor',
    stabilizeBase: 'Stabilize the Base',
    stabilizePowerHousing: 'Stabilize Power and Housing',
    pushBands: 'Push Chorus and Harmonics harder',
    investigateSummaryActive:
      'The Hero is searching the ruined base for the first usable clues.',
    investigateSummaryReady:
      'Use the Hero to inspect the base and reveal the next step.',
    investigateBlockerActive: 'Wait for the Hero to finish investigating.',
    investigateBlockerReady: 'The Hero will leave their current task when the action starts.',
    investigateReward: 'Unlock Explore Base.',
    exploreSummaryActive:
      'The Hero is searching deeper through the base to uncover repairs and salvage.',
    exploreSummaryReady:
      'Push beyond the first inspection to unlock base repairs and the first Crystal upgrade.',
    exploreBlockerActive: 'Wait for the Hero to finish exploring.',
    exploreReward: 'Unlock Restore Studio and Removing Moss.',
    studioSummaryActive: 'Builders are restoring the Studio so Chorus can come online.',
    studioSummaryReady: 'Spend Stone and assign builders to bring the Studio back online.',
    studioReward: 'Unlock Chorus staffing and early power growth.',
    firePitSummaryActive: 'Builders are assembling the Fire Pit to start the Vibes loop.',
    firePitSummaryReady: 'Build the Fire Pit to stabilize morale and open the route to recruitment.',
    firePitReward: 'Enable Vibes generation and recruitment prep.',
    reachSummary:
      'Grow the safe bubble by storing more Bassline and protecting field budget from overspending.',
    reachReward: 'Open the recruitment window at Survivor Cave.',
    recruitSummary:
      'Spend Vibes to recruit the first survivor and open the true crew growth loop.',
    recruitReward: 'Add a new crew member and widen base staffing options.',
    awaitArrivalTitle: 'Await Survivor Arrival',
    awaitArrivalSummary:
      'Your first recruit is already on the way. Keep the base stable while they travel.',
    awaitArrivalReward: 'Expand crew staffing and open the next growth loop.',
    stabilizeSummary:
      'You have opened the first growth loop. Improve power, staffing, processing, and housing to keep scaling.',
    stabilizeReward: 'A stronger and more readable base economy.',
    noPressure: 'No immediate pressure spike. Follow the visible bottlenecks.',
    readyForUpdate: 'Waiting for recruitment gate update.',
    recruitTheFirstSurvivor: 'Recruit the first survivor.',
    expandProcessing: 'Expand processing and recruitment in parallel.',
    moveOneBuilder: 'Move 1 crew into Construction.',
    keepOneBuilder: 'Keep at least 1 builder assigned.',
    assignScavenge: 'Assign Scavenge Crew for Stone.',
    keepScavenging: 'Keep scavenging until Fire Pit cost is covered.',
    assignBassline: 'Assign Bassline staff to grow the bubble.',
    storeBassline: 'Store Bassline and avoid overspending field budget.',
    waitFirePit: 'Wait for the Fire Pit to build enough Vibes.',
    assignFirePit: 'Assign Fire Pit crew for Vibes.',
    increaseChorus: 'Increase Chorus or turn off a station.',
    assignHarmonics: 'Assign crew to Harmonics.',
  },
  run: {
    kicker: 'Run',
    title: 'Save, Load, and Offline Return',
    clock: 'Clock',
    autosave: 'Autosave',
    whileAway: (duration: string) => `While you were away · ${duration}`,
    reach: 'Reach',
    recruits: 'Recruits',
    saveNow: 'Save Now',
    loadAutosave: 'Load Autosave',
    loadText: 'Load Text',
    resetRun: 'Reset Run',
    savePayload: 'Save Payload',
    noAutosave: 'No autosave',
  },
  dataTree: {
    title: 'Data Tree',
    subtitle: 'Catalog, schemas, and UI surfaces',
    search: 'Filter nodes',
    modes: {
      graph: 'Graph',
      timeline: 'Timeline',
    },
    graph: 'Graph Navigator',
    graphHint: 'Center a node, filter relation types, and simulate unlock impact.',
    graphSelected: 'Focused Node',
    graphEnabled: 'Enabled in Graph',
    graphEnable: 'Enable Node',
    graphDisable: 'Disable Node',
    graphReset: 'Clear Enabled',
    graphShowHidden: 'Show hidden nodes',
    graphEnabledNodes: 'Enabled Nodes',
    graphNoEnabled: 'No enabled nodes',
    graphPotentialUnlocks: 'Potential Unlocks',
    graphNoPotentialUnlocks: 'No unlock impact yet',
    graphIncoming: 'Depends On',
    graphOutgoing: 'Leads To',
    timeline: 'Story Timeline',
    timelineHint: 'Horizontal story lanes ordered by sequence, like a research tree.',
    timelineNoStory: 'No story beats available',
    timelineArc: 'Arc',
    timelineSequence: 'Sequence',
    empty: 'No matching nodes',
    selectNode: 'Select a node',
    definition: 'Definition',
    relations: 'Relations',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    visibility: 'Visibility',
    presentation: 'Presentation',
    currentState: 'Current State',
    visible: 'Visible',
    hidden: 'Hidden',
    kind: 'Kind',
    id: 'ID',
    label: 'Label',
    relatedIds: 'Related IDs',
    playerHint: 'Player Hint',
    cta: 'CTA',
    risk: 'Primary Risk',
    reveal: 'Reveal',
    shortLabel: 'Short Label',
    none: 'None',
    hiddenNode: 'Hidden',
    visibleNode: 'Visible',
    simulatedUnlock: 'Simulated Unlock',
    conditionsAll: 'All Of',
    conditionsAny: 'Any Of',
    filters: {
      all: 'All',
      unlock: 'Unlocks',
      blocker: 'Blockers',
      flow: 'Flows',
      access: 'Access',
      power: 'Power',
      model: 'Models',
      related: 'Related',
    },
    groups: {
      resources: 'Resources',
      roles: 'Roles',
      stations: 'Stations',
      construction: 'Construction',
      processing: 'Processing',
      actions: 'World Actions',
      story: 'Story Beats',
      flags: 'State Flags',
      models: 'Models',
      ui: 'UI Surfaces',
      tiles: 'Tiles',
      flora: 'Flora',
      structures: 'Structures',
    },
  },
  construction: {
    kicker: 'Construction',
    title: 'Build and Repair',
    crew: 'Construction Crew',
    note:
      'Bassline upgrades consume the same pool that defines bubble reach. Studio and Fire Pit projects are paid in Stone but still need builders on the job.',
    noActive: 'No active construction',
    statusReady: 'Ready',
    projectPaused: 'Project paused',
    needBuilders: 'Assign at least 1 Construction Crew.',
  },
  power: {
    kicker: 'Power',
    title: 'Power and Processing',
    resonanceChamber: 'Resonance Chamber',
    mixConsole: 'Mix Console',
    firePit: 'Fire Pit',
    harmonicsTier: 'Tier',
    chorusUpkeep: 'Chorus Upkeep',
    lifeSupport: 'Life Support',
    activeStaff: 'Active Staff',
    brownout: 'Brownout',
    note:
      'Chorus now covers both station upkeep and active life support. Harmonics improves Crystal efficiency and field conversion. Brownouts unpower the last requested station first and penalize band output.',
    unlockChorus: 'Restore Studio to unlock Chorus',
    unlockHarmonics: 'Build Resonance Chamber to unlock Harmonics',
  },
  base: {
    kicker: 'Base',
    title: 'Stone, Vibes, and Recruitment',
    stone: 'Stone',
    stoneStock: 'Stone Stock',
    vibes: 'Vibes',
    water: 'Water',
    waterStock: 'Water Stock',
    recruitCost: 'Recruit Cost',
    bunks: 'Bunks',
    housing: 'Housing',
    moraleDrain: 'Morale Drain',
    crewSpeed: 'Crew Speed',
    scavengeCrew: 'Scavenge Crew',
    firePitCrew: 'Fire Pit Crew',
    waterCrew: 'Water Crew',
    recruitSurvivor: 'Recruit Survivor',
    studioRestored: (bunks: number) => `Studio Restored · ${bunks} bunks`,
    studioDamagedReady: 'Studio Damaged · ready to restore',
    studioDamagedTutorial: 'Studio Damaged · tutorial gate active',
    firePitBuilt: (active: number) => `Fire Pit Built · ${active} active`,
    firePitNotBuilt: 'Fire Pit Not Built',
    pendingInstant: (pending: number, instant: number) => `Pending ${pending} · Instant ${instant}`,
    overcrowded: (multiplier: number) => `Overcrowded · x${multiplier.toFixed(2)}`,
    housingStable: 'Housing Stable',
    note:
      'Investigate and Explore are online-only and temporarily pull the Hero out of staffing. Water collection is available from run start. Completing the first Explore unlocks Restore Studio and Removing Moss.',
    recruitTravel: 'Recruit travel',
    nextRecruitCostSink: 'Next recruit cost',
    needMoreBunks: (count: number) => `Need ${count} more bunks`,
    stoneDepleted: 'Base stone stock depleted',
    waterDepleted: 'Base water stock depleted',
    prepBase: 'Prep Base',
  },
  admin: {
    simulation: {
      kicker: 'Simulation',
      title: 'Admin Controls',
      exportSave: 'Export Save',
      note:
        'This screen is for time controls, diagnostics, and save inspection. It is intentionally separate from the playable view.',
      tick10: 'Tick 10s',
      tick60: 'Tick 60s',
      offline1h: 'Offline +1h',
      offline4h: 'Offline +4h',
      clock: 'Clock',
      lifetimeGenerated: 'Lifetime Generated',
      lifetimeSpent: 'Lifetime Spent',
      crew: 'Crew',
      slots: 'Slots',
      builders: 'Builders',
      baseWater: 'Base Water',
      chorusPool: 'Chorus Pool',
      harmonicsPool: 'Harmonics Pool',
      badVibes: 'Bad Vibes',
      badVibesMult: 'Bad Vibes Mult',
      pendingRecruits: 'Pending Recruits',
      nextRecruit: 'Next Recruit',
      reach: 'Reach',
      frontier: 'Frontier',
      target: 'Target',
      budget: 'Budget',
      powerUpkeep: 'Power Upkeep',
      harmonicsTier: 'Harmonics Tier',
      inertia: 'Inertia',
      degrade: 'Degrade',
    },
    construction: {
      kicker: 'Construction',
      title: 'Current Job',
    },
    spending: {
      kicker: 'Spending',
      title: 'Bassline Sink',
      spend10: 'Spend 10',
      spend25: 'Spend 25',
      spend50: 'Spend 50',
      spendAll: 'Spend All',
    },
    diagnostics: {
      kicker: 'Diagnostics',
      title: 'Snapshot Notes',
    },
    persistence: {
      kicker: 'Persistence',
      title: 'Export Preview',
      empty: 'No save exported yet.',
    },
  },
} as const
