## OpenStreetMap-compatible constants for hex map features
## Based on https://wiki.openstreetmap.org/wiki/Map_features
class_name OSMConstants
extends RefCounted

# =============================================================================
# HIGHWAY - Roads, paths, and transportation routes
# =============================================================================
enum Highway {
	NONE,
	# Major roads
	MOTORWAY,
	TRUNK,
	PRIMARY,
	SECONDARY,
	TERTIARY,
	UNCLASSIFIED,
	RESIDENTIAL,
	# Link roads
	MOTORWAY_LINK,
	TRUNK_LINK,
	PRIMARY_LINK,
	SECONDARY_LINK,
	TERTIARY_LINK,
	# Special roads
	LIVING_STREET,
	SERVICE,
	PEDESTRIAN,
	TRACK,
	BUS_GUIDEWAY,
	BUSWAY,
	RACEWAY,
	ROAD,
	# Paths
	FOOTWAY,
	CYCLEWAY,
	BRIDLEWAY,
	PATH,
	STEPS,
	CORRIDOR,
}

const HIGHWAY_NAMES := {
	Highway.NONE: "none",
	Highway.MOTORWAY: "motorway",
	Highway.TRUNK: "trunk",
	Highway.PRIMARY: "primary",
	Highway.SECONDARY: "secondary",
	Highway.TERTIARY: "tertiary",
	Highway.UNCLASSIFIED: "unclassified",
	Highway.RESIDENTIAL: "residential",
	Highway.MOTORWAY_LINK: "motorway_link",
	Highway.TRUNK_LINK: "trunk_link",
	Highway.PRIMARY_LINK: "primary_link",
	Highway.SECONDARY_LINK: "secondary_link",
	Highway.TERTIARY_LINK: "tertiary_link",
	Highway.LIVING_STREET: "living_street",
	Highway.SERVICE: "service",
	Highway.PEDESTRIAN: "pedestrian",
	Highway.TRACK: "track",
	Highway.BUS_GUIDEWAY: "bus_guideway",
	Highway.BUSWAY: "busway",
	Highway.RACEWAY: "raceway",
	Highway.ROAD: "road",
	Highway.FOOTWAY: "footway",
	Highway.CYCLEWAY: "cycleway",
	Highway.BRIDLEWAY: "bridleway",
	Highway.PATH: "path",
	Highway.STEPS: "steps",
	Highway.CORRIDOR: "corridor",
}

# =============================================================================
# LANDUSE - Primary use of land
# =============================================================================
enum Landuse {
	NONE,
	# Developed
	COMMERCIAL,
	RETAIL,
	RESIDENTIAL,
	INDUSTRIAL,
	EDUCATION,
	INSTITUTIONAL,
	CONSTRUCTION,
	FAIRGROUND,
	# Rural/Agricultural
	FARMLAND,
	MEADOW,
	FOREST,
	ORCHARD,
	VINEYARD,
	ALLOTMENTS,
	AQUACULTURE,
	ANIMAL_KEEPING,
	# Transportation
	RAILWAY,
	HIGHWAY,
	DEPOT,
	PORT,
	GARAGES,
	# Other
	CEMETERY,
	MILITARY,
	QUARRY,
	LANDFILL,
	GRASS,
	BROWNFIELD,
	GREENFIELD,
	BASIN,
	RESERVOIR,
	SALT_POND,
	RECREATION_GROUND,
	VILLAGE_GREEN,
	FLOWERBED,
	PLANT_NURSERY,
	GREENHOUSE_HORTICULTURE,
	RELIGIOUS,
}

const LANDUSE_NAMES := {
	Landuse.NONE: "none",
	Landuse.COMMERCIAL: "commercial",
	Landuse.RETAIL: "retail",
	Landuse.RESIDENTIAL: "residential",
	Landuse.INDUSTRIAL: "industrial",
	Landuse.EDUCATION: "education",
	Landuse.INSTITUTIONAL: "institutional",
	Landuse.CONSTRUCTION: "construction",
	Landuse.FAIRGROUND: "fairground",
	Landuse.FARMLAND: "farmland",
	Landuse.MEADOW: "meadow",
	Landuse.FOREST: "forest",
	Landuse.ORCHARD: "orchard",
	Landuse.VINEYARD: "vineyard",
	Landuse.ALLOTMENTS: "allotments",
	Landuse.AQUACULTURE: "aquaculture",
	Landuse.ANIMAL_KEEPING: "animal_keeping",
	Landuse.RAILWAY: "railway",
	Landuse.HIGHWAY: "highway",
	Landuse.DEPOT: "depot",
	Landuse.PORT: "port",
	Landuse.GARAGES: "garages",
	Landuse.CEMETERY: "cemetery",
	Landuse.MILITARY: "military",
	Landuse.QUARRY: "quarry",
	Landuse.LANDFILL: "landfill",
	Landuse.GRASS: "grass",
	Landuse.BROWNFIELD: "brownfield",
	Landuse.GREENFIELD: "greenfield",
	Landuse.BASIN: "basin",
	Landuse.RESERVOIR: "reservoir",
	Landuse.SALT_POND: "salt_pond",
	Landuse.RECREATION_GROUND: "recreation_ground",
	Landuse.VILLAGE_GREEN: "village_green",
	Landuse.FLOWERBED: "flowerbed",
	Landuse.PLANT_NURSERY: "plant_nursery",
	Landuse.GREENHOUSE_HORTICULTURE: "greenhouse_horticulture",
	Landuse.RELIGIOUS: "religious",
}

# =============================================================================
# NATURAL - Physical geography features
# =============================================================================
enum Natural {
	NONE,
	# Vegetation
	FELL,
	GRASSLAND,
	HEATH,
	MOOR,
	SCRUB,
	SHRUBBERY,
	TREE,
	TREE_ROW,
	TREE_STUMP,
	TUNDRA,
	WOOD,
	# Water
	BAY,
	BEACH,
	BLOWHOLE,
	CAPE,
	COASTLINE,
	CREVASSE,
	GEYSER,
	GLACIER,
	HOT_SPRING,
	ISTHMUS,
	MUD,
	PENINSULA,
	REEF,
	SHINGLE,
	SHOAL,
	SPRING,
	STRAIT,
	WATER,
	WETLAND,
	# Geology/Landforms
	ARCH,
	ARETE,
	BARE_ROCK,
	BLOCKFIELD,
	CAVE_ENTRANCE,
	CLIFF,
	DUNE,
	EARTH_BANK,
	FUMAROLE,
	GULLY,
	HILL,
	PEAK,
	RIDGE,
	ROCK,
	SADDLE,
	SAND,
	SCREE,
	SINKHOLE,
	STONE,
	VALLEY,
	VOLCANO,
}

const NATURAL_NAMES := {
	Natural.NONE: "none",
	Natural.FELL: "fell",
	Natural.GRASSLAND: "grassland",
	Natural.HEATH: "heath",
	Natural.MOOR: "moor",
	Natural.SCRUB: "scrub",
	Natural.SHRUBBERY: "shrubbery",
	Natural.TREE: "tree",
	Natural.TREE_ROW: "tree_row",
	Natural.TREE_STUMP: "tree_stump",
	Natural.TUNDRA: "tundra",
	Natural.WOOD: "wood",
	Natural.BAY: "bay",
	Natural.BEACH: "beach",
	Natural.BLOWHOLE: "blowhole",
	Natural.CAPE: "cape",
	Natural.COASTLINE: "coastline",
	Natural.CREVASSE: "crevasse",
	Natural.GEYSER: "geyser",
	Natural.GLACIER: "glacier",
	Natural.HOT_SPRING: "hot_spring",
	Natural.ISTHMUS: "isthmus",
	Natural.MUD: "mud",
	Natural.PENINSULA: "peninsula",
	Natural.REEF: "reef",
	Natural.SHINGLE: "shingle",
	Natural.SHOAL: "shoal",
	Natural.SPRING: "spring",
	Natural.STRAIT: "strait",
	Natural.WATER: "water",
	Natural.WETLAND: "wetland",
	Natural.ARCH: "arch",
	Natural.ARETE: "arete",
	Natural.BARE_ROCK: "bare_rock",
	Natural.BLOCKFIELD: "blockfield",
	Natural.CAVE_ENTRANCE: "cave_entrance",
	Natural.CLIFF: "cliff",
	Natural.DUNE: "dune",
	Natural.EARTH_BANK: "earth_bank",
	Natural.FUMAROLE: "fumarole",
	Natural.GULLY: "gully",
	Natural.HILL: "hill",
	Natural.PEAK: "peak",
	Natural.RIDGE: "ridge",
	Natural.ROCK: "rock",
	Natural.SADDLE: "saddle",
	Natural.SAND: "sand",
	Natural.SCREE: "scree",
	Natural.SINKHOLE: "sinkhole",
	Natural.STONE: "stone",
	Natural.VALLEY: "valley",
	Natural.VOLCANO: "volcano",
}

# =============================================================================
# BUILDING - Structures
# =============================================================================
enum Building {
	NONE,
	YES,  # Generic building
	# Residential
	APARTMENTS,
	BARRACKS,
	BUNGALOW,
	CABIN,
	DETACHED,
	DORMITORY,
	FARM,
	HOUSE,
	HOTEL,
	RESIDENTIAL,
	SEMIDETACHED_HOUSE,
	TERRACE,
	TREE_HOUSE,
	# Commercial
	COMMERCIAL,
	INDUSTRIAL,
	KIOSK,
	OFFICE,
	RETAIL,
	SUPERMARKET,
	WAREHOUSE,
	# Religious
	CATHEDRAL,
	CHAPEL,
	CHURCH,
	KINGDOM_HALL,
	MONASTERY,
	MOSQUE,
	PRESBYTERY,
	SHRINE,
	SYNAGOGUE,
	TEMPLE,
	# Civic
	FIRE_STATION,
	GOVERNMENT,
	HOSPITAL,
	KINDERGARTEN,
	MUSEUM,
	SCHOOL,
	TRAIN_STATION,
	UNIVERSITY,
	PUBLIC,
	CIVIC,
	# Agricultural
	BARN,
	CONSERVATORY,
	COWSHED,
	FARM_AUXILIARY,
	GREENHOUSE,
	STABLE,
	STY,
	# Sports
	GRANDSTAND,
	PAVILION,
	RIDING_HALL,
	SPORTS_HALL,
	SPORTS_CENTRE,
	STADIUM,
	# Storage
	BOATHOUSE,
	HANGAR,
	HUT,
	SHED,
	# Cars
	CARPORT,
	GARAGE,
	GARAGES,
	PARKING,
	# Power/Technical
	DIGESTER,
	SERVICE,
	TRANSFORMER_TOWER,
	WATER_TOWER,
	SILO,
	# Other
	BEACH_HUT,
	BUNKER,
	CASTLE,
	CONSTRUCTION,
	CONTAINER,
	RUINS,
	TOWER,
	WINDMILL,
	GATEHOUSE,
	ROOF,
	BRIDGE,
	ENTRANCE,
}

const BUILDING_NAMES := {
	Building.NONE: "none",
	Building.YES: "yes",
	Building.APARTMENTS: "apartments",
	Building.BARRACKS: "barracks",
	Building.BUNGALOW: "bungalow",
	Building.CABIN: "cabin",
	Building.DETACHED: "detached",
	Building.DORMITORY: "dormitory",
	Building.FARM: "farm",
	Building.HOUSE: "house",
	Building.HOTEL: "hotel",
	Building.RESIDENTIAL: "residential",
	Building.SEMIDETACHED_HOUSE: "semidetached_house",
	Building.TERRACE: "terrace",
	Building.TREE_HOUSE: "tree_house",
	Building.COMMERCIAL: "commercial",
	Building.INDUSTRIAL: "industrial",
	Building.KIOSK: "kiosk",
	Building.OFFICE: "office",
	Building.RETAIL: "retail",
	Building.SUPERMARKET: "supermarket",
	Building.WAREHOUSE: "warehouse",
	Building.CATHEDRAL: "cathedral",
	Building.CHAPEL: "chapel",
	Building.CHURCH: "church",
	Building.KINGDOM_HALL: "kingdom_hall",
	Building.MONASTERY: "monastery",
	Building.MOSQUE: "mosque",
	Building.PRESBYTERY: "presbytery",
	Building.SHRINE: "shrine",
	Building.SYNAGOGUE: "synagogue",
	Building.TEMPLE: "temple",
	Building.FIRE_STATION: "fire_station",
	Building.GOVERNMENT: "government",
	Building.HOSPITAL: "hospital",
	Building.KINDERGARTEN: "kindergarten",
	Building.MUSEUM: "museum",
	Building.SCHOOL: "school",
	Building.TRAIN_STATION: "train_station",
	Building.UNIVERSITY: "university",
	Building.PUBLIC: "public",
	Building.CIVIC: "civic",
	Building.BARN: "barn",
	Building.CONSERVATORY: "conservatory",
	Building.COWSHED: "cowshed",
	Building.FARM_AUXILIARY: "farm_auxiliary",
	Building.GREENHOUSE: "greenhouse",
	Building.STABLE: "stable",
	Building.STY: "sty",
	Building.GRANDSTAND: "grandstand",
	Building.PAVILION: "pavilion",
	Building.RIDING_HALL: "riding_hall",
	Building.SPORTS_HALL: "sports_hall",
	Building.SPORTS_CENTRE: "sports_centre",
	Building.STADIUM: "stadium",
	Building.BOATHOUSE: "boathouse",
	Building.HANGAR: "hangar",
	Building.HUT: "hut",
	Building.SHED: "shed",
	Building.CARPORT: "carport",
	Building.GARAGE: "garage",
	Building.GARAGES: "garages",
	Building.PARKING: "parking",
	Building.DIGESTER: "digester",
	Building.SERVICE: "service",
	Building.TRANSFORMER_TOWER: "transformer_tower",
	Building.WATER_TOWER: "water_tower",
	Building.SILO: "silo",
	Building.BEACH_HUT: "beach_hut",
	Building.BUNKER: "bunker",
	Building.CASTLE: "castle",
	Building.CONSTRUCTION: "construction",
	Building.CONTAINER: "container",
	Building.RUINS: "ruins",
	Building.TOWER: "tower",
	Building.WINDMILL: "windmill",
	Building.GATEHOUSE: "gatehouse",
	Building.ROOF: "roof",
	Building.BRIDGE: "bridge",
	Building.ENTRANCE: "entrance",
}

# =============================================================================
# AMENITY - Facilities for visitors and residents
# =============================================================================
enum Amenity {
	NONE,
	# Sustenance
	BAR,
	BIERGARTEN,
	CAFE,
	FAST_FOOD,
	FOOD_COURT,
	ICE_CREAM,
	PUB,
	RESTAURANT,
	# Education
	COLLEGE,
	DANCING_SCHOOL,
	DRIVING_SCHOOL,
	KINDERGARTEN,
	LIBRARY,
	SCHOOL,
	UNIVERSITY,
	MUSIC_SCHOOL,
	LANGUAGE_SCHOOL,
	# Transportation
	BICYCLE_PARKING,
	BICYCLE_RENTAL,
	BOAT_RENTAL,
	BUS_STATION,
	CAR_RENTAL,
	CAR_WASH,
	CHARGING_STATION,
	FERRY_TERMINAL,
	FUEL,
	PARKING,
	PARKING_ENTRANCE,
	PARKING_SPACE,
	TAXI,
	# Financial
	ATM,
	BANK,
	BUREAU_DE_CHANGE,
	MONEY_TRANSFER,
	PAYMENT_TERMINAL,
	# Healthcare
	CLINIC,
	DENTIST,
	DOCTORS,
	HOSPITAL,
	PHARMACY,
	VETERINARY,
	NURSING_HOME,
	SOCIAL_FACILITY,
	# Entertainment
	ARTS_CENTRE,
	BROTHEL,
	CASINO,
	CINEMA,
	COMMUNITY_CENTRE,
	CONFERENCE_CENTRE,
	EVENTS_VENUE,
	GAMBLING,
	NIGHTCLUB,
	PLANETARIUM,
	THEATRE,
	# Public Service
	COURTHOUSE,
	EMBASSY,
	FIRE_STATION,
	POLICE,
	POST_BOX,
	POST_OFFICE,
	PRISON,
	RANGER_STATION,
	TOWNHALL,
	# Facilities
	BBQUE,
	BENCH,
	CLOCK,
	DRINKING_WATER,
	GIVE_BOX,
	LOUNGE,
	PARCEL_LOCKER,
	SHELTER,
	SHOWER,
	TELEPHONE,
	TOILETS,
	WATER_POINT,
	# Waste
	RECYCLING,
	WASTE_BASKET,
	WASTE_DISPOSAL,
	WASTE_TRANSFER_STATION,
	# Religion
	GRAVE_YARD,
	MONASTERY,
	PLACE_OF_WORSHIP,
	# Other
	ANIMAL_BOARDING,
	ANIMAL_SHELTER,
	CHILDCARE,
	FOUNTAIN,
	HUNTING_STAND,
	INTERNET_CAFE,
	KITCHEN,
	MARKETPLACE,
	PUBLIC_BATH,
	PUBLIC_BOOKCASE,
	VENDING_MACHINE,
	WORKSHOP,
}

const AMENITY_NAMES := {
	Amenity.NONE: "none",
	Amenity.BAR: "bar",
	Amenity.BIERGARTEN: "biergarten",
	Amenity.CAFE: "cafe",
	Amenity.FAST_FOOD: "fast_food",
	Amenity.FOOD_COURT: "food_court",
	Amenity.ICE_CREAM: "ice_cream",
	Amenity.PUB: "pub",
	Amenity.RESTAURANT: "restaurant",
	Amenity.COLLEGE: "college",
	Amenity.DANCING_SCHOOL: "dancing_school",
	Amenity.DRIVING_SCHOOL: "driving_school",
	Amenity.KINDERGARTEN: "kindergarten",
	Amenity.LIBRARY: "library",
	Amenity.SCHOOL: "school",
	Amenity.UNIVERSITY: "university",
	Amenity.MUSIC_SCHOOL: "music_school",
	Amenity.LANGUAGE_SCHOOL: "language_school",
	Amenity.BICYCLE_PARKING: "bicycle_parking",
	Amenity.BICYCLE_RENTAL: "bicycle_rental",
	Amenity.BOAT_RENTAL: "boat_rental",
	Amenity.BUS_STATION: "bus_station",
	Amenity.CAR_RENTAL: "car_rental",
	Amenity.CAR_WASH: "car_wash",
	Amenity.CHARGING_STATION: "charging_station",
	Amenity.FERRY_TERMINAL: "ferry_terminal",
	Amenity.FUEL: "fuel",
	Amenity.PARKING: "parking",
	Amenity.PARKING_ENTRANCE: "parking_entrance",
	Amenity.PARKING_SPACE: "parking_space",
	Amenity.TAXI: "taxi",
	Amenity.ATM: "atm",
	Amenity.BANK: "bank",
	Amenity.BUREAU_DE_CHANGE: "bureau_de_change",
	Amenity.MONEY_TRANSFER: "money_transfer",
	Amenity.PAYMENT_TERMINAL: "payment_terminal",
	Amenity.CLINIC: "clinic",
	Amenity.DENTIST: "dentist",
	Amenity.DOCTORS: "doctors",
	Amenity.HOSPITAL: "hospital",
	Amenity.PHARMACY: "pharmacy",
	Amenity.VETERINARY: "veterinary",
	Amenity.NURSING_HOME: "nursing_home",
	Amenity.SOCIAL_FACILITY: "social_facility",
	Amenity.ARTS_CENTRE: "arts_centre",
	Amenity.BROTHEL: "brothel",
	Amenity.CASINO: "casino",
	Amenity.CINEMA: "cinema",
	Amenity.COMMUNITY_CENTRE: "community_centre",
	Amenity.CONFERENCE_CENTRE: "conference_centre",
	Amenity.EVENTS_VENUE: "events_venue",
	Amenity.GAMBLING: "gambling",
	Amenity.NIGHTCLUB: "nightclub",
	Amenity.PLANETARIUM: "planetarium",
	Amenity.THEATRE: "theatre",
	Amenity.COURTHOUSE: "courthouse",
	Amenity.EMBASSY: "embassy",
	Amenity.FIRE_STATION: "fire_station",
	Amenity.POLICE: "police",
	Amenity.POST_BOX: "post_box",
	Amenity.POST_OFFICE: "post_office",
	Amenity.PRISON: "prison",
	Amenity.RANGER_STATION: "ranger_station",
	Amenity.TOWNHALL: "townhall",
	Amenity.BBQUE: "bbq",
	Amenity.BENCH: "bench",
	Amenity.CLOCK: "clock",
	Amenity.DRINKING_WATER: "drinking_water",
	Amenity.GIVE_BOX: "give_box",
	Amenity.LOUNGE: "lounge",
	Amenity.PARCEL_LOCKER: "parcel_locker",
	Amenity.SHELTER: "shelter",
	Amenity.SHOWER: "shower",
	Amenity.TELEPHONE: "telephone",
	Amenity.TOILETS: "toilets",
	Amenity.WATER_POINT: "water_point",
	Amenity.RECYCLING: "recycling",
	Amenity.WASTE_BASKET: "waste_basket",
	Amenity.WASTE_DISPOSAL: "waste_disposal",
	Amenity.WASTE_TRANSFER_STATION: "waste_transfer_station",
	Amenity.GRAVE_YARD: "grave_yard",
	Amenity.MONASTERY: "monastery",
	Amenity.PLACE_OF_WORSHIP: "place_of_worship",
	Amenity.ANIMAL_BOARDING: "animal_boarding",
	Amenity.ANIMAL_SHELTER: "animal_shelter",
	Amenity.CHILDCARE: "childcare",
	Amenity.FOUNTAIN: "fountain",
	Amenity.HUNTING_STAND: "hunting_stand",
	Amenity.INTERNET_CAFE: "internet_cafe",
	Amenity.KITCHEN: "kitchen",
	Amenity.MARKETPLACE: "marketplace",
	Amenity.PUBLIC_BATH: "public_bath",
	Amenity.PUBLIC_BOOKCASE: "public_bookcase",
	Amenity.VENDING_MACHINE: "vending_machine",
	Amenity.WORKSHOP: "workshop",
}

# =============================================================================
# LEISURE - Recreation and leisure facilities
# =============================================================================
enum Leisure {
	NONE,
	ADULT_GAMING_CENTRE,
	AMUSEMENT_ARCADE,
	BANDSTAND,
	BATHING_PLACE,
	BEACH_RESORT,
	BIRD_HIDE,
	BOWLING_ALLEY,
	COMMON,
	DANCE,
	DISC_GOLF_COURSE,
	DOG_PARK,
	ESCAPE_GAME,
	FIREPIT,
	FISHING,
	FITNESS_CENTRE,
	FITNESS_STATION,
	GARDEN,
	GOLF_COURSE,
	HACKERSPACE,
	HORSE_RIDING,
	ICE_RINK,
	MARINA,
	MINIATURE_GOLF,
	NATURE_RESERVE,
	OUTDOOR_SEATING,
	PARK,
	PICNIC_TABLE,
	PITCH,
	PLAYGROUND,
	RESORT,
	SAUNA,
	SLIPWAY,
	SPORTS_CENTRE,
	SPORTS_HALL,
	STADIUM,
	SUMMER_CAMP,
	SWIMMING_AREA,
	SWIMMING_POOL,
	TRACK,
	TRAMPOLINE_PARK,
	WATER_PARK,
}

const LEISURE_NAMES := {
	Leisure.NONE: "none",
	Leisure.ADULT_GAMING_CENTRE: "adult_gaming_centre",
	Leisure.AMUSEMENT_ARCADE: "amusement_arcade",
	Leisure.BANDSTAND: "bandstand",
	Leisure.BATHING_PLACE: "bathing_place",
	Leisure.BEACH_RESORT: "beach_resort",
	Leisure.BIRD_HIDE: "bird_hide",
	Leisure.BOWLING_ALLEY: "bowling_alley",
	Leisure.COMMON: "common",
	Leisure.DANCE: "dance",
	Leisure.DISC_GOLF_COURSE: "disc_golf_course",
	Leisure.DOG_PARK: "dog_park",
	Leisure.ESCAPE_GAME: "escape_game",
	Leisure.FIREPIT: "firepit",
	Leisure.FISHING: "fishing",
	Leisure.FITNESS_CENTRE: "fitness_centre",
	Leisure.FITNESS_STATION: "fitness_station",
	Leisure.GARDEN: "garden",
	Leisure.GOLF_COURSE: "golf_course",
	Leisure.HACKERSPACE: "hackerspace",
	Leisure.HORSE_RIDING: "horse_riding",
	Leisure.ICE_RINK: "ice_rink",
	Leisure.MARINA: "marina",
	Leisure.MINIATURE_GOLF: "miniature_golf",
	Leisure.NATURE_RESERVE: "nature_reserve",
	Leisure.OUTDOOR_SEATING: "outdoor_seating",
	Leisure.PARK: "park",
	Leisure.PICNIC_TABLE: "picnic_table",
	Leisure.PITCH: "pitch",
	Leisure.PLAYGROUND: "playground",
	Leisure.RESORT: "resort",
	Leisure.SAUNA: "sauna",
	Leisure.SLIPWAY: "slipway",
	Leisure.SPORTS_CENTRE: "sports_centre",
	Leisure.SPORTS_HALL: "sports_hall",
	Leisure.STADIUM: "stadium",
	Leisure.SUMMER_CAMP: "summer_camp",
	Leisure.SWIMMING_AREA: "swimming_area",
	Leisure.SWIMMING_POOL: "swimming_pool",
	Leisure.TRACK: "track",
	Leisure.TRAMPOLINE_PARK: "trampoline_park",
	Leisure.WATER_PARK: "water_park",
}

# =============================================================================
# TOURISM - Tourist attractions and accommodation
# =============================================================================
enum Tourism {
	NONE,
	# Accommodation
	ALPINE_HUT,
	APARTMENT,
	CAMP_PITCH,
	CAMP_SITE,
	CARAVAN_SITE,
	CHALET,
	GUEST_HOUSE,
	HOSTEL,
	HOTEL,
	MOTEL,
	WILDERNESS_HUT,
	# Attractions
	AQUARIUM,
	ARTWORK,
	ATTRACTION,
	GALLERY,
	MUSEUM,
	THEME_PARK,
	VIEWPOINT,
	ZOO,
	# Information
	INFORMATION,
	PICNIC_SITE,
}

const TOURISM_NAMES := {
	Tourism.NONE: "none",
	Tourism.ALPINE_HUT: "alpine_hut",
	Tourism.APARTMENT: "apartment",
	Tourism.CAMP_PITCH: "camp_pitch",
	Tourism.CAMP_SITE: "camp_site",
	Tourism.CARAVAN_SITE: "caravan_site",
	Tourism.CHALET: "chalet",
	Tourism.GUEST_HOUSE: "guest_house",
	Tourism.HOSTEL: "hostel",
	Tourism.HOTEL: "hotel",
	Tourism.MOTEL: "motel",
	Tourism.WILDERNESS_HUT: "wilderness_hut",
	Tourism.AQUARIUM: "aquarium",
	Tourism.ARTWORK: "artwork",
	Tourism.ATTRACTION: "attraction",
	Tourism.GALLERY: "gallery",
	Tourism.MUSEUM: "museum",
	Tourism.THEME_PARK: "theme_park",
	Tourism.VIEWPOINT: "viewpoint",
	Tourism.ZOO: "zoo",
	Tourism.INFORMATION: "information",
	Tourism.PICNIC_SITE: "picnic_site",
}

# =============================================================================
# WATERWAY - Rivers, streams, canals
# =============================================================================
enum Waterway {
	NONE,
	# Natural
	RIVER,
	STREAM,
	TIDAL_CHANNEL,
	# Artificial
	CANAL,
	DRAIN,
	DITCH,
	PRESSURISED,
	FAIRWAY,
	FISH_PASS,
	CANOE_PASS,
	# Facilities
	DOCK,
	BOATYARD,
	# Barriers
	DAM,
	WEIR,
	WATERFALL,
	RAPIDS,
	LOCK_GATE,
	SLUICE_GATE,
	TURNING_POINT,
	WATER_POINT,
	FUEL,
}

const WATERWAY_NAMES := {
	Waterway.NONE: "none",
	Waterway.RIVER: "river",
	Waterway.STREAM: "stream",
	Waterway.TIDAL_CHANNEL: "tidal_channel",
	Waterway.CANAL: "canal",
	Waterway.DRAIN: "drain",
	Waterway.DITCH: "ditch",
	Waterway.PRESSURISED: "pressurised",
	Waterway.FAIRWAY: "fairway",
	Waterway.FISH_PASS: "fish_pass",
	Waterway.CANOE_PASS: "canoe_pass",
	Waterway.DOCK: "dock",
	Waterway.BOATYARD: "boatyard",
	Waterway.DAM: "dam",
	Waterway.WEIR: "weir",
	Waterway.WATERFALL: "waterfall",
	Waterway.RAPIDS: "rapids",
	Waterway.LOCK_GATE: "lock_gate",
	Waterway.SLUICE_GATE: "sluice_gate",
	Waterway.TURNING_POINT: "turning_point",
	Waterway.WATER_POINT: "water_point",
	Waterway.FUEL: "fuel",
}

# =============================================================================
# MAN_MADE - Artificial structures (not buildings)
# =============================================================================
enum ManMade {
	NONE,
	# Infrastructure
	BRIDGE,
	TUNNEL,
	PIPELINE,
	UTILITY_POLE,
	COMMUNICATIONS_TOWER,
	ANTENNA,
	MAST,
	TOWER,
	# Industrial
	CHIMNEY,
	COOLING_TOWER,
	CRANE,
	GASOMETER,
	PETROLEUM_WELL,
	SILO,
	STORAGE_TANK,
	WASTEWATER_PLANT,
	WATER_TOWER,
	WATER_WELL,
	WATER_WORKS,
	WINDMILL,
	WORKS,
	# Barriers
	BREAKWATER,
	CUTLINE,
	DYKE,
	EMBANKMENT,
	GROYNE,
	# Transport
	PIER,
	QUAY,
	# Other
	ADIT,
	BEACON,
	CAIRN,
	CROSS,
	FLAGPOLE,
	LIGHTHOUSE,
	MINESHAFT,
	MONITORING_STATION,
	OBSERVATORY,
	OBELISK,
	RESERVOIR_COVERED,
	SHAFT,
	STREET_CABINET,
	SURVEILLANCE,
	SURVEY_POINT,
	WATERMILL,
	WILDLIFE_CROSSING,
}

const MAN_MADE_NAMES := {
	ManMade.NONE: "none",
	ManMade.BRIDGE: "bridge",
	ManMade.TUNNEL: "tunnel",
	ManMade.PIPELINE: "pipeline",
	ManMade.UTILITY_POLE: "utility_pole",
	ManMade.COMMUNICATIONS_TOWER: "communications_tower",
	ManMade.ANTENNA: "antenna",
	ManMade.MAST: "mast",
	ManMade.TOWER: "tower",
	ManMade.CHIMNEY: "chimney",
	ManMade.COOLING_TOWER: "cooling_tower",
	ManMade.CRANE: "crane",
	ManMade.GASOMETER: "gasometer",
	ManMade.PETROLEUM_WELL: "petroleum_well",
	ManMade.SILO: "silo",
	ManMade.STORAGE_TANK: "storage_tank",
	ManMade.WASTEWATER_PLANT: "wastewater_plant",
	ManMade.WATER_TOWER: "water_tower",
	ManMade.WATER_WELL: "water_well",
	ManMade.WATER_WORKS: "water_works",
	ManMade.WINDMILL: "windmill",
	ManMade.WORKS: "works",
	ManMade.BREAKWATER: "breakwater",
	ManMade.CUTLINE: "cutline",
	ManMade.DYKE: "dyke",
	ManMade.EMBANKMENT: "embankment",
	ManMade.GROYNE: "groyne",
	ManMade.PIER: "pier",
	ManMade.QUAY: "quay",
	ManMade.ADIT: "adit",
	ManMade.BEACON: "beacon",
	ManMade.CAIRN: "cairn",
	ManMade.CROSS: "cross",
	ManMade.FLAGPOLE: "flagpole",
	ManMade.LIGHTHOUSE: "lighthouse",
	ManMade.MINESHAFT: "mineshaft",
	ManMade.MONITORING_STATION: "monitoring_station",
	ManMade.OBSERVATORY: "observatory",
	ManMade.OBELISK: "obelisk",
	ManMade.RESERVOIR_COVERED: "reservoir_covered",
	ManMade.SHAFT: "shaft",
	ManMade.STREET_CABINET: "street_cabinet",
	ManMade.SURVEILLANCE: "surveillance",
	ManMade.SURVEY_POINT: "survey_point",
	ManMade.WATERMILL: "watermill",
	ManMade.WILDLIFE_CROSSING: "wildlife_crossing",
}

# =============================================================================
# SURFACE - Ground surface type
# =============================================================================
enum Surface {
	NONE,
	# Paved
	PAVED,
	ASPHALT,
	CONCRETE,
	PAVING_STONES,
	SETT,
	COBBLESTONE,
	METAL,
	WOOD,
	# Unpaved
	UNPAVED,
	COMPACTED,
	FINE_GRAVEL,
	GRAVEL,
	PEBBLESTONE,
	DIRT,
	EARTH,
	GRASS,
	MUD,
	SAND,
	GROUND,
	# Special
	ICE,
	SNOW,
	CLAY,
	TARTAN,
	ARTIFICIAL_TURF,
	RUBBER,
}

const SURFACE_NAMES := {
	Surface.NONE: "none",
	Surface.PAVED: "paved",
	Surface.ASPHALT: "asphalt",
	Surface.CONCRETE: "concrete",
	Surface.PAVING_STONES: "paving_stones",
	Surface.SETT: "sett",
	Surface.COBBLESTONE: "cobblestone",
	Surface.METAL: "metal",
	Surface.WOOD: "wood",
	Surface.UNPAVED: "unpaved",
	Surface.COMPACTED: "compacted",
	Surface.FINE_GRAVEL: "fine_gravel",
	Surface.GRAVEL: "gravel",
	Surface.PEBBLESTONE: "pebblestone",
	Surface.DIRT: "dirt",
	Surface.EARTH: "earth",
	Surface.GRASS: "grass",
	Surface.MUD: "mud",
	Surface.SAND: "sand",
	Surface.GROUND: "ground",
	Surface.ICE: "ice",
	Surface.SNOW: "snow",
	Surface.CLAY: "clay",
	Surface.TARTAN: "tartan",
	Surface.ARTIFICIAL_TURF: "artificial_turf",
	Surface.RUBBER: "rubber",
}

# =============================================================================
# ACCESS - Access restrictions
# =============================================================================
enum Access {
	NONE,
	YES,
	NO,
	PRIVATE,
	PERMISSIVE,
	AGRICULTURAL,
	FORESTRY,
	DELIVERY,
	DESIGNATED,
	DESTINATION,
	CUSTOMERS,
	DISMOUNT,
	PERMIT,
	MILITARY,
}

const ACCESS_NAMES := {
	Access.NONE: "none",
	Access.YES: "yes",
	Access.NO: "no",
	Access.PRIVATE: "private",
	Access.PERMISSIVE: "permissive",
	Access.AGRICULTURAL: "agricultural",
	Access.FORESTRY: "forestry",
	Access.DELIVERY: "delivery",
	Access.DESIGNATED: "designated",
	Access.DESTINATION: "destination",
	Access.CUSTOMERS: "customers",
	Access.DISMOUNT: "dismount",
	Access.PERMIT: "permit",
	Access.MILITARY: "military",
}

# =============================================================================
# SHOP - Retail establishments
# =============================================================================
enum Shop {
	NONE,
	# Food
	ALCOHOL,
	BAKERY,
	BEVERAGES,
	BREWING_SUPPLIES,
	BUTCHER,
	CHEESE,
	CHOCOLATE,
	COFFEE,
	CONFECTIONERY,
	CONVENIENCE,
	DELI,
	DAIRY,
	FARM,
	FROZEN_FOOD,
	GREENGROCER,
	HEALTH_FOOD,
	ICE_CREAM,
	PASTA,
	PASTRY,
	SEAFOOD,
	SPICES,
	TEA,
	SUPERMARKET,
	# General
	DEPARTMENT_STORE,
	GENERAL,
	KIOSK,
	MALL,
	WHOLESALE,
	# Clothing
	BABY_GOODS,
	BAG,
	BOUTIQUE,
	CLOTHES,
	FASHION_ACCESSORIES,
	JEWELRY,
	LEATHER,
	SHOES,
	TAILOR,
	WATCHES,
	# Home
	ANTIQUES,
	BED,
	CARPET,
	CURTAIN,
	DOORS,
	FLOORING,
	FURNITURE,
	HARDWARE,
	HOUSEWARE,
	INTERIOR_DECORATION,
	KITCHEN,
	PAINT,
	TILES,
	WINDOW_BLIND,
	# Electronics
	COMPUTER,
	ELECTRONICS,
	HIFI,
	MOBILE_PHONE,
	VACUUM_CLEANER,
	# Other
	ART,
	BEAUTY,
	BOOKS,
	CHEMIST,
	COSMETICS,
	FLORIST,
	FUNERAL_DIRECTORS,
	GIFT,
	HAIRDRESSER,
	LAUNDRY,
	LOTTERY,
	MEDICAL_SUPPLY,
	MUSIC,
	NEWSAGENT,
	OPTICIAN,
	PET,
	PHOTO,
	SPORTS,
	STATIONERY,
	TOBACCO,
	TOYS,
	TRAVEL_AGENCY,
	VARIETY_STORE,
	VIDEO,
	VIDEO_GAMES,
	WEAPONS,
}

const SHOP_NAMES := {
	Shop.NONE: "none",
	Shop.ALCOHOL: "alcohol",
	Shop.BAKERY: "bakery",
	Shop.BEVERAGES: "beverages",
	Shop.BREWING_SUPPLIES: "brewing_supplies",
	Shop.BUTCHER: "butcher",
	Shop.CHEESE: "cheese",
	Shop.CHOCOLATE: "chocolate",
	Shop.COFFEE: "coffee",
	Shop.CONFECTIONERY: "confectionery",
	Shop.CONVENIENCE: "convenience",
	Shop.DELI: "deli",
	Shop.DAIRY: "dairy",
	Shop.FARM: "farm",
	Shop.FROZEN_FOOD: "frozen_food",
	Shop.GREENGROCER: "greengrocer",
	Shop.HEALTH_FOOD: "health_food",
	Shop.ICE_CREAM: "ice_cream",
	Shop.PASTA: "pasta",
	Shop.PASTRY: "pastry",
	Shop.SEAFOOD: "seafood",
	Shop.SPICES: "spices",
	Shop.TEA: "tea",
	Shop.SUPERMARKET: "supermarket",
	Shop.DEPARTMENT_STORE: "department_store",
	Shop.GENERAL: "general",
	Shop.KIOSK: "kiosk",
	Shop.MALL: "mall",
	Shop.WHOLESALE: "wholesale",
	Shop.BABY_GOODS: "baby_goods",
	Shop.BAG: "bag",
	Shop.BOUTIQUE: "boutique",
	Shop.CLOTHES: "clothes",
	Shop.FASHION_ACCESSORIES: "fashion_accessories",
	Shop.JEWELRY: "jewelry",
	Shop.LEATHER: "leather",
	Shop.SHOES: "shoes",
	Shop.TAILOR: "tailor",
	Shop.WATCHES: "watches",
	Shop.ANTIQUES: "antiques",
	Shop.BED: "bed",
	Shop.CARPET: "carpet",
	Shop.CURTAIN: "curtain",
	Shop.DOORS: "doors",
	Shop.FLOORING: "flooring",
	Shop.FURNITURE: "furniture",
	Shop.HARDWARE: "hardware",
	Shop.HOUSEWARE: "houseware",
	Shop.INTERIOR_DECORATION: "interior_decoration",
	Shop.KITCHEN: "kitchen",
	Shop.PAINT: "paint",
	Shop.TILES: "tiles",
	Shop.WINDOW_BLIND: "window_blind",
	Shop.COMPUTER: "computer",
	Shop.ELECTRONICS: "electronics",
	Shop.HIFI: "hifi",
	Shop.MOBILE_PHONE: "mobile_phone",
	Shop.VACUUM_CLEANER: "vacuum_cleaner",
	Shop.ART: "art",
	Shop.BEAUTY: "beauty",
	Shop.BOOKS: "books",
	Shop.CHEMIST: "chemist",
	Shop.COSMETICS: "cosmetics",
	Shop.FLORIST: "florist",
	Shop.FUNERAL_DIRECTORS: "funeral_directors",
	Shop.GIFT: "gift",
	Shop.HAIRDRESSER: "hairdresser",
	Shop.LAUNDRY: "laundry",
	Shop.LOTTERY: "lottery",
	Shop.MEDICAL_SUPPLY: "medical_supply",
	Shop.MUSIC: "music",
	Shop.NEWSAGENT: "newsagent",
	Shop.OPTICIAN: "optician",
	Shop.PET: "pet",
	Shop.PHOTO: "photo",
	Shop.SPORTS: "sports",
	Shop.STATIONERY: "stationery",
	Shop.TOBACCO: "tobacco",
	Shop.TOYS: "toys",
	Shop.TRAVEL_AGENCY: "travel_agency",
	Shop.VARIETY_STORE: "variety_store",
	Shop.VIDEO: "video",
	Shop.VIDEO_GAMES: "video_games",
	Shop.WEAPONS: "weapons",
}

# =============================================================================
# BARRIER - Physical barriers
# =============================================================================
enum Barrier {
	NONE,
	# Linear
	FENCE,
	WALL,
	HEDGE,
	GUARD_RAIL,
	RETAINING_WALL,
	CITY_WALL,
	DITCH,
	HANDRAIL,
	KERB,
	# Access
	GATE,
	LIFT_GATE,
	SWING_GATE,
	TOLL_BOOTH,
	TURNSTILE,
	ENTRANCE,
	CATTLE_GRID,
	STILE,
	BOLLARD,
	CHAIN,
	BLOCK,
	JERSEY_BARRIER,
}

const BARRIER_NAMES := {
	Barrier.NONE: "none",
	Barrier.FENCE: "fence",
	Barrier.WALL: "wall",
	Barrier.HEDGE: "hedge",
	Barrier.GUARD_RAIL: "guard_rail",
	Barrier.RETAINING_WALL: "retaining_wall",
	Barrier.CITY_WALL: "city_wall",
	Barrier.DITCH: "ditch",
	Barrier.HANDRAIL: "handrail",
	Barrier.KERB: "kerb",
	Barrier.GATE: "gate",
	Barrier.LIFT_GATE: "lift_gate",
	Barrier.SWING_GATE: "swing_gate",
	Barrier.TOLL_BOOTH: "toll_booth",
	Barrier.TURNSTILE: "turnstile",
	Barrier.ENTRANCE: "entrance",
	Barrier.CATTLE_GRID: "cattle_grid",
	Barrier.STILE: "stile",
	Barrier.BOLLARD: "bollard",
	Barrier.CHAIN: "chain",
	Barrier.BLOCK: "block",
	Barrier.JERSEY_BARRIER: "jersey_barrier",
}

# =============================================================================
# POWER - Electrical infrastructure
# =============================================================================
enum Power {
	NONE,
	LINE,
	MINOR_LINE,
	CABLE,
	PLANT,
	GENERATOR,
	SUBSTATION,
	TRANSFORMER,
	POLE,
	TOWER,
	PORTAL,
	CATENARY_MAST,
	SWITCH,
	COMPENSATOR,
}

const POWER_NAMES := {
	Power.NONE: "none",
	Power.LINE: "line",
	Power.MINOR_LINE: "minor_line",
	Power.CABLE: "cable",
	Power.PLANT: "plant",
	Power.GENERATOR: "generator",
	Power.SUBSTATION: "substation",
	Power.TRANSFORMER: "transformer",
	Power.POLE: "pole",
	Power.TOWER: "tower",
	Power.PORTAL: "portal",
	Power.CATENARY_MAST: "catenary_mast",
	Power.SWITCH: "switch",
	Power.COMPENSATOR: "compensator",
}

# =============================================================================
# RAILWAY - Rail infrastructure
# =============================================================================
enum Railway {
	NONE,
	RAIL,
	LIGHT_RAIL,
	SUBWAY,
	TRAM,
	MONORAIL,
	NARROW_GAUGE,
	PRESERVED,
	MINIATURE,
	FUNICULAR,
	# Stations
	STATION,
	HALT,
	TRAM_STOP,
	SUBWAY_ENTRANCE,
	PLATFORM,
	# Infrastructure
	CROSSING,
	LEVEL_CROSSING,
	SIGNAL,
	SWITCH,
	TURNTABLE,
	ROUNDHOUSE,
	BUFFER_STOP,
	DERAIL,
	RAILWAY_CROSSING,
}

const RAILWAY_NAMES := {
	Railway.NONE: "none",
	Railway.RAIL: "rail",
	Railway.LIGHT_RAIL: "light_rail",
	Railway.SUBWAY: "subway",
	Railway.TRAM: "tram",
	Railway.MONORAIL: "monorail",
	Railway.NARROW_GAUGE: "narrow_gauge",
	Railway.PRESERVED: "preserved",
	Railway.MINIATURE: "miniature",
	Railway.FUNICULAR: "funicular",
	Railway.STATION: "station",
	Railway.HALT: "halt",
	Railway.TRAM_STOP: "tram_stop",
	Railway.SUBWAY_ENTRANCE: "subway_entrance",
	Railway.PLATFORM: "platform",
	Railway.CROSSING: "crossing",
	Railway.LEVEL_CROSSING: "level_crossing",
	Railway.SIGNAL: "signal",
	Railway.SWITCH: "switch",
	Railway.TURNTABLE: "turntable",
	Railway.ROUNDHOUSE: "roundhouse",
	Railway.BUFFER_STOP: "buffer_stop",
	Railway.DERAIL: "derail",
	Railway.RAILWAY_CROSSING: "railway_crossing",
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

static func enum_to_string(enum_dict: Dictionary, value: int) -> String:
	return str(enum_dict.get(value, "none"))

static func string_to_enum(names_dict: Dictionary, name: String) -> int:
	for key in names_dict:
		if names_dict[key] == name:
			return key
	return 0  # NONE

static func get_enum_options(names_dict: Dictionary) -> Array[String]:
	var options: Array[String] = []
	for value in names_dict.values():
		options.append(str(value))
	options.sort()
	return options
