import type { ConstructionOptionDef } from "../runtime/protocol"

// Authored content: construction options (source of truth). codegen -> Rust `const CONSTRUCTION_OPTIONS`.
export const CONSTRUCTION_OPTIONS: readonly ConstructionOptionDef[] = [
  {
    id: "construction.slot_capacity", schemaId: "construction.slot_capacity", label: "Slot Capacity", group: "crystal_upgrade",
    cost: { kind: "drain_per_worker_second", resource_id: "resource.bassline", amount: 0.45 },
    duration: { kind: "crystal_level_scaled", track: "slot_capacity", base_seconds: 55, per_level_seconds: 20 },
    requirements: [],
    effects: [{ kind: "increment_crystal_track", track: "slot_capacity", amount: 1 }],
    uiOrder: 10,
  },
  {
    id: "construction.output", schemaId: "construction.output", label: "Output", group: "crystal_upgrade",
    cost: { kind: "drain_per_worker_second", resource_id: "resource.bassline", amount: 0.45 },
    duration: { kind: "crystal_level_scaled", track: "output", base_seconds: 35, per_level_seconds: 12 },
    requirements: [],
    effects: [{ kind: "increment_crystal_track", track: "output", amount: 1 }],
    uiOrder: 20,
  },
  {
    id: "construction.storage", schemaId: "construction.storage", label: "Storage", group: "crystal_upgrade",
    cost: { kind: "drain_per_worker_second", resource_id: "resource.bassline", amount: 0.45 },
    duration: { kind: "crystal_level_scaled", track: "storage", base_seconds: 28, per_level_seconds: 10 },
    requirements: [],
    effects: [{ kind: "increment_crystal_track", track: "storage", amount: 1 }],
    uiOrder: 30,
  },
  {
    id: "construction.removing_moss", schemaId: "construction.removing_moss", label: "Removing Moss", group: "crystal_upgrade",
    cost: { kind: "time_only" },
    duration: { kind: "fixed", seconds: 10 },
    requirements: [{ kind: "flag_set", flag_id: "crystal.removing_moss_unlocked" }, { kind: "flag_unset", flag_id: "crystal.removing_moss_completed" }],
    effects: [{ kind: "set_flag", flag_id: "crystal.removing_moss_completed", value: true }],
    uiOrder: 40,
  },
  {
    id: "construction.polish_field", schemaId: "construction.polish_field", label: "Polish Crystal Base", group: "crystal_upgrade",
    cost: { kind: "upfront_bundle", costs: [{ item_id: "cost.skin", amount: 1 }, { item_id: "resource.water", amount: 5 }] },
    duration: { kind: "fixed", seconds: 4 },
    requirements: [{ kind: "flag_set", flag_id: "base.tutorial_explored" }],
    effects: [{ kind: "increment_crystal_track", track: "field_polish", amount: 1 }],
    uiOrder: 45,
  },
  {
    id: "project.restore_studio", schemaId: "project.restore_studio", label: "Restore Studio", group: "base_project",
    cost: { kind: "upfront", resource_id: "resource.stone", amount: 600 },
    duration: { kind: "fixed", seconds: 12 },
    requirements: [{ kind: "flag_set", flag_id: "base.studio_restore_unlocked" }, { kind: "flag_unset", flag_id: "base.studio_restored" }],
    effects: [{ kind: "set_flag", flag_id: "base.studio_restored", value: true }, { kind: "add_bunks", amount: 15 }],
    uiOrder: 50,
  },
  {
    id: "project.build_fire_pit", schemaId: "project.build_fire_pit", label: "Build Fire Pit", group: "base_project",
    cost: { kind: "upfront", resource_id: "resource.stone", amount: 200 },
    duration: { kind: "fixed", seconds: 4 },
    requirements: [{ kind: "flag_unset", flag_id: "base.fire_pit_built" }],
    effects: [{ kind: "set_flag", flag_id: "base.fire_pit_built", value: true }],
    uiOrder: 60,
  },
  {
    id: "project.build_resonance_chamber", schemaId: "project.build_resonance_chamber", label: "Build Resonance Chamber", group: "base_project",
    cost: { kind: "upfront", resource_id: "resource.stone", amount: 320 },
    duration: { kind: "fixed", seconds: 8 },
    requirements: [{ kind: "flag_set", flag_id: "base.studio_restored" }, { kind: "flag_unset", flag_id: "base.resonance_chamber_built" }],
    effects: [{ kind: "set_flag", flag_id: "base.resonance_chamber_built", value: true }],
    uiOrder: 70,
  },
  {
    id: "project.build_mix_console", schemaId: "project.build_mix_console", label: "Build Mix Console", group: "base_project",
    cost: { kind: "upfront", resource_id: "resource.stone", amount: 420 },
    duration: { kind: "fixed", seconds: 10 },
    requirements: [{ kind: "flag_set", flag_id: "base.studio_restored" }, { kind: "flag_set", flag_id: "base.resonance_chamber_built" }, { kind: "flag_unset", flag_id: "base.mix_console_built" }],
    effects: [{ kind: "set_flag", flag_id: "base.mix_console_built", value: true }],
    uiOrder: 80,
  },
  {
    id: "project.build_workshop", schemaId: "project.build_workshop", label: "Build Workshop", group: "base_project",
    cost: { kind: "upfront", resource_id: "resource.stone", amount: 260 },
    duration: { kind: "fixed", seconds: 8 },
    requirements: [{ kind: "flag_set", flag_id: "base.studio_restored" }, { kind: "flag_unset", flag_id: "base.workshop_built" }],
    effects: [{ kind: "set_flag", flag_id: "base.workshop_built", value: true }],
    uiOrder: 90,
  },
  {
    id: "project.build_research_booth", schemaId: "project.build_research_booth", label: "Build Research Booth", group: "base_project",
    cost: { kind: "upfront", resource_id: "resource.stone", amount: 360 },
    duration: { kind: "fixed", seconds: 10 },
    requirements: [{ kind: "flag_set", flag_id: "base.studio_restored" }, { kind: "flag_set", flag_id: "base.resonance_chamber_built" }, { kind: "flag_unset", flag_id: "base.research_booth_built" }],
    effects: [{ kind: "set_flag", flag_id: "base.research_booth_built", value: true }],
    uiOrder: 100,
  },
]
