// @generated by `npm run content:build` from packages/add-domain/src/content/{construction,world-actions,processing}.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const CONSTRUCTION_OPTIONS: &[ConstructionOptionDef] = &[
    ConstructionOptionDef {
        id: CONSTRUCTION_SLOT_CAPACITY,
        schema_id: CONSTRUCTION_SLOT_CAPACITY,
        label: "Slot Capacity",
        group: ConstructionGroup::CrystalUpgrade,
        cost: CostDef::DrainPerWorkerSecond {
            resource_id: "resource.bassline",
            amount: 0.45,
        },
        duration: DurationDef::CrystalLevelScaled {
            track: CrystalTrack::SlotCapacity,
            base_seconds: 55.0,
            per_level_seconds: 20.0,
        },
        requirements: &[],
        effects: &[EffectDef::IncrementCrystalTrack {
            track: CrystalTrack::SlotCapacity,
            amount: 1,
        }],
        ui_order: 10,
    },
    ConstructionOptionDef {
        id: CONSTRUCTION_OUTPUT,
        schema_id: CONSTRUCTION_OUTPUT,
        label: "Output",
        group: ConstructionGroup::CrystalUpgrade,
        cost: CostDef::DrainPerWorkerSecond {
            resource_id: "resource.bassline",
            amount: 0.45,
        },
        duration: DurationDef::CrystalLevelScaled {
            track: CrystalTrack::Output,
            base_seconds: 35.0,
            per_level_seconds: 12.0,
        },
        requirements: &[],
        effects: &[EffectDef::IncrementCrystalTrack {
            track: CrystalTrack::Output,
            amount: 1,
        }],
        ui_order: 20,
    },
    ConstructionOptionDef {
        id: CONSTRUCTION_STORAGE,
        schema_id: CONSTRUCTION_STORAGE,
        label: "Storage",
        group: ConstructionGroup::CrystalUpgrade,
        cost: CostDef::DrainPerWorkerSecond {
            resource_id: "resource.bassline",
            amount: 0.45,
        },
        duration: DurationDef::CrystalLevelScaled {
            track: CrystalTrack::Storage,
            base_seconds: 28.0,
            per_level_seconds: 10.0,
        },
        requirements: &[],
        effects: &[EffectDef::IncrementCrystalTrack {
            track: CrystalTrack::Storage,
            amount: 1,
        }],
        ui_order: 30,
    },
    ConstructionOptionDef {
        id: CONSTRUCTION_REMOVING_MOSS,
        schema_id: CONSTRUCTION_REMOVING_MOSS,
        label: "Removing Moss",
        group: ConstructionGroup::CrystalUpgrade,
        cost: CostDef::TimeOnly,
        duration: DurationDef::Fixed { seconds: 10.0 },
        requirements: &[
            RequirementDef::FlagSet(FLAG_CRYSTAL_REMOVING_MOSS_UNLOCKED),
            RequirementDef::FlagUnset(FLAG_CRYSTAL_REMOVING_MOSS_COMPLETED),
        ],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_CRYSTAL_REMOVING_MOSS_COMPLETED,
            value: true,
        }],
        ui_order: 40,
    },
    ConstructionOptionDef {
        id: CONSTRUCTION_POLISH_FIELD,
        schema_id: CONSTRUCTION_POLISH_FIELD,
        label: "Polish Crystal Base",
        group: ConstructionGroup::CrystalUpgrade,
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "cost.skin",
                    amount: 1.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 5.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 4.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_TUTORIAL_EXPLORED)],
        effects: &[EffectDef::IncrementCrystalTrack {
            track: CrystalTrack::FieldPolish,
            amount: 1,
        }],
        ui_order: 45,
    },
    ConstructionOptionDef {
        id: PROJECT_RESTORE_STUDIO,
        schema_id: PROJECT_RESTORE_STUDIO,
        label: "Restore Studio",
        group: ConstructionGroup::BaseProject,
        cost: CostDef::Upfront {
            resource_id: "resource.stone",
            amount: 600.0,
        },
        duration: DurationDef::Fixed { seconds: 12.0 },
        requirements: &[
            RequirementDef::FlagSet(FLAG_BASE_STUDIO_RESTORE_UNLOCKED),
            RequirementDef::FlagUnset(FLAG_BASE_STUDIO_RESTORED),
        ],
        effects: &[
            EffectDef::SetFlag {
                flag_id: FLAG_BASE_STUDIO_RESTORED,
                value: true,
            },
            EffectDef::AddBunks { amount: 15 },
        ],
        ui_order: 50,
    },
    ConstructionOptionDef {
        id: PROJECT_BUILD_FIRE_PIT,
        schema_id: PROJECT_BUILD_FIRE_PIT,
        label: "Build Fire Pit",
        group: ConstructionGroup::BaseProject,
        cost: CostDef::Upfront {
            resource_id: "resource.stone",
            amount: 200.0,
        },
        duration: DurationDef::Fixed { seconds: 4.0 },
        requirements: &[RequirementDef::FlagUnset(FLAG_BASE_FIRE_PIT_BUILT)],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_BASE_FIRE_PIT_BUILT,
            value: true,
        }],
        ui_order: 60,
    },
    ConstructionOptionDef {
        id: PROJECT_BUILD_RESONANCE_CHAMBER,
        schema_id: PROJECT_BUILD_RESONANCE_CHAMBER,
        label: "Build Resonance Chamber",
        group: ConstructionGroup::BaseProject,
        cost: CostDef::Upfront {
            resource_id: "resource.stone",
            amount: 320.0,
        },
        duration: DurationDef::Fixed { seconds: 8.0 },
        requirements: &[
            RequirementDef::FlagSet(FLAG_BASE_STUDIO_RESTORED),
            RequirementDef::FlagUnset(FLAG_BASE_RESONANCE_CHAMBER_BUILT),
        ],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_BASE_RESONANCE_CHAMBER_BUILT,
            value: true,
        }],
        ui_order: 70,
    },
    ConstructionOptionDef {
        id: PROJECT_BUILD_MIX_CONSOLE,
        schema_id: PROJECT_BUILD_MIX_CONSOLE,
        label: "Build Mix Console",
        group: ConstructionGroup::BaseProject,
        cost: CostDef::Upfront {
            resource_id: "resource.stone",
            amount: 420.0,
        },
        duration: DurationDef::Fixed { seconds: 10.0 },
        requirements: &[
            RequirementDef::FlagSet(FLAG_BASE_STUDIO_RESTORED),
            RequirementDef::FlagSet(FLAG_BASE_RESONANCE_CHAMBER_BUILT),
            RequirementDef::FlagUnset(FLAG_BASE_MIX_CONSOLE_BUILT),
        ],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_BASE_MIX_CONSOLE_BUILT,
            value: true,
        }],
        ui_order: 80,
    },
    ConstructionOptionDef {
        id: PROJECT_BUILD_WORKSHOP,
        schema_id: PROJECT_BUILD_WORKSHOP,
        label: "Build Workshop",
        group: ConstructionGroup::BaseProject,
        cost: CostDef::Upfront {
            resource_id: "resource.stone",
            amount: 260.0,
        },
        duration: DurationDef::Fixed { seconds: 8.0 },
        requirements: &[
            RequirementDef::FlagSet(FLAG_BASE_STUDIO_RESTORED),
            RequirementDef::FlagUnset(FLAG_BASE_WORKSHOP_BUILT),
        ],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_BASE_WORKSHOP_BUILT,
            value: true,
        }],
        ui_order: 90,
    },
    ConstructionOptionDef {
        id: PROJECT_BUILD_RESEARCH_BOOTH,
        schema_id: PROJECT_BUILD_RESEARCH_BOOTH,
        label: "Build Research Booth",
        group: ConstructionGroup::BaseProject,
        cost: CostDef::Upfront {
            resource_id: "resource.stone",
            amount: 360.0,
        },
        duration: DurationDef::Fixed { seconds: 10.0 },
        requirements: &[
            RequirementDef::FlagSet(FLAG_BASE_STUDIO_RESTORED),
            RequirementDef::FlagSet(FLAG_BASE_RESONANCE_CHAMBER_BUILT),
            RequirementDef::FlagUnset(FLAG_BASE_RESEARCH_BOOTH_BUILT),
        ],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_BASE_RESEARCH_BOOTH_BUILT,
            value: true,
        }],
        ui_order: 100,
    },
];

pub(in crate::game_data) const WORLD_ACTIONS: &[WorldActionDef] = &[
    WorldActionDef {
        id: WORLD_ACTION_INVESTIGATE_BASE,
        schema_id: WORLD_ACTION_INVESTIGATE_BASE,
        label: "Investigate Base",
        duration_seconds: 5.0,
        hero_only: true,
        offline_progress: false,
        hero_exposure: HeroExposureDef::Studio,
        return_to_bubble_seconds: 0.0,
        return_to_studio_seconds: 0.0,
        requirements: &[RequirementDef::FlagUnset(FLAG_BASE_TUTORIAL_INVESTIGATED)],
        effects: &[EffectDef::SetFlag {
            flag_id: FLAG_BASE_TUTORIAL_INVESTIGATED,
            value: true,
        }],
        ui_order: 10,
    },
    WorldActionDef {
        id: WORLD_ACTION_EXPLORE_BASE,
        schema_id: WORLD_ACTION_EXPLORE_BASE,
        label: "Explore Base",
        duration_seconds: 10.0,
        hero_only: true,
        offline_progress: false,
        hero_exposure: HeroExposureDef::OutsideBubble,
        return_to_bubble_seconds: 2.0,
        return_to_studio_seconds: 4.0,
        requirements: &[
            RequirementDef::FlagSet(FLAG_BASE_TUTORIAL_INVESTIGATED),
            RequirementDef::FlagUnset(FLAG_BASE_TUTORIAL_EXPLORED),
        ],
        effects: &[
            EffectDef::SetFlag {
                flag_id: FLAG_BASE_TUTORIAL_EXPLORED,
                value: true,
            },
            EffectDef::SetFlag {
                flag_id: FLAG_BASE_STUDIO_RESTORE_UNLOCKED,
                value: true,
            },
            EffectDef::SetFlag {
                flag_id: FLAG_CRYSTAL_REMOVING_MOSS_UNLOCKED,
                value: true,
            },
            EffectDef::SetFlag {
                flag_id: FLAG_BASE_WATER_COLLECTION_UNLOCKED,
                value: true,
            },
            EffectDef::AddSkins { amount: 1 },
        ],
        ui_order: 20,
    },
];

pub(in crate::game_data) const PROCESSING_RECIPES: &[ProcessingRecipeDef] = &[
    ProcessingRecipeDef {
        id: RECIPE_RESONANCE_FIELD_CALIBRATION,
        schema_id: RECIPE_RESONANCE_FIELD_CALIBRATION,
        label: "Field Calibration",
        station_id: "station.resonance_chamber",
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "resource.stone",
                    amount: 80.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 1.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 10.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_RESONANCE_CHAMBER_BUILT)],
        effects: &[EffectDef::IncrementProcessingTrack {
            track: ProcessingTrack::ResonanceCalibration,
            amount: 1,
        }],
        max_level: 5,
        ui_order: 10,
    },
    ProcessingRecipeDef {
        id: RECIPE_MIX_SIGNAL_BALANCING,
        schema_id: RECIPE_MIX_SIGNAL_BALANCING,
        label: "Signal Balancing",
        station_id: "station.mix_console",
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "resource.stone",
                    amount: 120.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 2.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 12.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_MIX_CONSOLE_BUILT)],
        effects: &[EffectDef::IncrementProcessingTrack {
            track: ProcessingTrack::MixCalibration,
            amount: 1,
        }],
        max_level: 5,
        ui_order: 20,
    },
    ProcessingRecipeDef {
        id: RECIPE_WORKSHOP_BUILDER_TOOLS,
        schema_id: RECIPE_WORKSHOP_BUILDER_TOOLS,
        label: "Builder Tools",
        station_id: "station.workshop",
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "resource.stone",
                    amount: 100.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 2.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 14.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_WORKSHOP_BUILT)],
        effects: &[EffectDef::IncrementProcessingTrack {
            track: ProcessingTrack::WorkshopTooling,
            amount: 1,
        }],
        max_level: 5,
        ui_order: 30,
    },
    ProcessingRecipeDef {
        id: RECIPE_WORKSHOP_WATER_CONDENSERS,
        schema_id: RECIPE_WORKSHOP_WATER_CONDENSERS,
        label: "Water Condensers",
        station_id: "station.workshop",
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "resource.stone",
                    amount: 70.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 2.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 12.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_WORKSHOP_BUILT)],
        effects: &[EffectDef::IncrementProcessingTrack {
            track: ProcessingTrack::WorkshopWaterCondensers,
            amount: 1,
        }],
        max_level: 5,
        ui_order: 40,
    },
    ProcessingRecipeDef {
        id: RECIPE_RESEARCH_CHORUS_ROUTING,
        schema_id: RECIPE_RESEARCH_CHORUS_ROUTING,
        label: "Chorus Routing",
        station_id: "station.research_booth",
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "resource.stone",
                    amount: 140.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 1.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 16.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_RESEARCH_BOOTH_BUILT)],
        effects: &[EffectDef::IncrementProcessingTrack {
            track: ProcessingTrack::ResearchChorusRouting,
            amount: 1,
        }],
        max_level: 5,
        ui_order: 50,
    },
    ProcessingRecipeDef {
        id: RECIPE_RESEARCH_HARMONIC_STUDY,
        schema_id: RECIPE_RESEARCH_HARMONIC_STUDY,
        label: "Harmonic Study",
        station_id: "station.research_booth",
        cost: CostDef::UpfrontBundle {
            costs: &[
                CostItemDef {
                    item_id: "resource.stone",
                    amount: 180.0,
                },
                CostItemDef {
                    item_id: "resource.water",
                    amount: 2.0,
                },
            ],
        },
        duration: DurationDef::Fixed { seconds: 18.0 },
        requirements: &[RequirementDef::FlagSet(FLAG_BASE_RESEARCH_BOOTH_BUILT)],
        effects: &[EffectDef::IncrementProcessingTrack {
            track: ProcessingTrack::ResearchHarmonicStudy,
            amount: 1,
        }],
        max_level: 5,
        ui_order: 60,
    },
];
