// @generated by `npm run content:build` from packages/add-domain/src/content/items.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const ITEMS: &[ItemDef] = &[
    ItemDef {
        id: "item.scrap_metal",
        label: "Scrap Metal",
        stackable: true,
        max_stack: 99,
    },
    ItemDef {
        id: "item.ration",
        label: "Ration",
        stackable: true,
        max_stack: 20,
    },
    ItemDef {
        id: "item.echo_shard",
        label: "Echo Shard",
        stackable: true,
        max_stack: 50,
    },
    ItemDef {
        id: "item.field_kit",
        label: "Field Kit",
        stackable: false,
        max_stack: 1,
    },
];
