// @generated by `npm run content:build` from packages/add-domain/src/content/perks.ts.
// Do not edit by hand; edit the TS source and re-run the generator.

use crate::game_data::*;

pub(in crate::game_data) const PERKS: &[PerkDef] = &[
    PerkDef {
        id: "perk.scavenger",
        label: "Scavenger",
        requires: &[],
        effects: &[PerkEffectDef {
            stat: PerkStat::ScavengeYield,
            multiplier: 1.25,
        }],
    },
    PerkDef {
        id: "perk.steady_hands",
        label: "Steady Hands",
        requires: &[],
        effects: &[PerkEffectDef {
            stat: PerkStat::ConstructionSpeed,
            multiplier: 1.15,
        }],
    },
    PerkDef {
        id: "perk.crystal_attuned",
        label: "Crystal Attuned",
        requires: &["perk.steady_hands"],
        effects: &[PerkEffectDef {
            stat: PerkStat::CrystalOutput,
            multiplier: 1.15,
        }],
    },
    PerkDef {
        id: "perk.field_medic",
        label: "Field Medic",
        requires: &[],
        effects: &[PerkEffectDef {
            stat: PerkStat::HeroRecovery,
            multiplier: 1.3,
        }],
    },
];
