use crate::game_data::*;

pub(in crate::game_data) const ROLES: &[RoleDef] = &[
    RoleDef {
        id: ROLE_CRYSTAL_BASSLINE,
        schema_id: ROLE_CRYSTAL_BASSLINE,
        label: "Crystal: Bassline",
        slot_pool: RoleSlotPool::CrystalCircle,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: None,
        ui_section: "crystal",
        ui_order: 10,
    },
    RoleDef {
        id: ROLE_CRYSTAL_CHORUS,
        schema_id: ROLE_CRYSTAL_CHORUS,
        label: "Crystal: Chorus",
        slot_pool: RoleSlotPool::CrystalCircle,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: None,
        ui_section: "crystal",
        ui_order: 20,
    },
    RoleDef {
        id: ROLE_CRYSTAL_HARMONICS,
        schema_id: ROLE_CRYSTAL_HARMONICS,
        label: "Crystal: Harmonics",
        slot_pool: RoleSlotPool::CrystalCircle,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: None,
        ui_section: "crystal",
        ui_order: 30,
    },
    RoleDef {
        id: ROLE_CONSTRUCTION,
        schema_id: ROLE_CONSTRUCTION,
        label: "Construction",
        slot_pool: RoleSlotPool::Base,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: None,
        ui_section: "construction",
        ui_order: 40,
    },
    RoleDef {
        id: ROLE_FIRE_PIT,
        schema_id: ROLE_FIRE_PIT,
        label: "Fire Pit: Vibes",
        slot_pool: RoleSlotPool::FirePit,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: Some(2),
        ui_section: "base",
        ui_order: 30,
    },
    RoleDef {
        id: ROLE_SCAVENGE,
        schema_id: ROLE_SCAVENGE,
        label: "Base: Scavenge",
        slot_pool: RoleSlotPool::Base,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: None,
        ui_section: "base",
        ui_order: 40,
    },
    RoleDef {
        id: ROLE_WATER,
        schema_id: ROLE_WATER,
        label: "Base: Water",
        slot_pool: RoleSlotPool::Base,
        hero_allowed: true,
        crew_allowed: true,
        max_crew_slots: None,
        ui_section: "base",
        ui_order: 50,
    },
];
