import type {
  VisualAssetCatalog,
  VisualAssetFootprint,
  VisualAssetFrameMetadata,
  VisualAssetInteractionMetadata,
  VisualAssetOcclusionMode,
  VisualAssetPoint,
  VisualAssetThemeTag,
  VisualTokenDefinition,
} from "@aedventure/game-assets"
import {
  compileSemanticMapDefinition,
  tileSpawnPoint,
  validateCompiledMap,
  type CompiledSemanticMap,
  type MapSpawnPoint,
  type MapValidation,
  type SemanticMapDefinition,
  type SemanticWallPlacement,
} from "@aedventure/game-map"

export type RpgIdleEntityKind = "hero_unit" | "resource_node" | "building_site"
export type RpgIdleActionId = "gather_wood"

export interface RpgIdleEntity {
  readonly id: string
  readonly kind: RpgIdleEntityKind
  readonly label: string
  readonly tokenId?: string
  readonly tile?: {
    readonly x: number
    readonly y: number
  }
  readonly spawnPointId?: string
  readonly interactionZoneId?: string
}

export interface RpgIdleAction {
  readonly id: RpgIdleActionId
  readonly label: string
  readonly targetEntityId: string
  readonly requiredZoneId: string
  readonly resourceDelta: {
    readonly wood: number
  }
}

export interface RpgIdleDemoMap {
  readonly id: "rpg_idle_grove"
  readonly label: "Grove Outpost"
  readonly definition: SemanticMapDefinition
  readonly compiled: CompiledSemanticMap
  readonly spawnPoints: readonly MapSpawnPoint[]
  readonly validation: MapValidation
}

const TILE_SIZE = 32
const SOURCE_ID = "internal.generated.rpg.procedural_v1"
const TILESET_ID = "tileset.internal.rpg.procedural"
const ATLAS_ID = "atlas.internal.rpg.procedural_v1"

interface FrameOptions {
  readonly collisionFootprint?: VisualAssetFootprint
  readonly visualFootprint?: VisualAssetFootprint
  readonly shadowFootprint?: VisualAssetFootprint
  readonly zAnchor?: VisualAssetPoint
  readonly interaction?: VisualAssetInteractionMetadata
  readonly themeTags?: readonly VisualAssetThemeTag[]
  readonly occlusionMode?: VisualAssetOcclusionMode
}

export const RPG_IDLE_DEMO_CATALOG: VisualAssetCatalog = {
  version: 1,
  tileSize: TILE_SIZE,
  sources: [
    {
      id: SOURCE_ID,
      status: "target_approved",
      filePath: "apps/rpg-idle-demo/public/assets/rpg-idle-atlas.manifest.json",
      sourceUrl: "internal://aedventure/rpg-idle/procedural/v1",
      author: "Aedventure project",
      license: "AGPL-3.0-or-later",
      attributionText:
        "Runtime procedural RPG/idle placeholder visuals generated by the Aedventure project.",
      redistributionAllowed: "yes",
      commercialUseAllowed: "yes",
      bundledInTargetApp: true,
      notes:
        "Procedural metadata only. The shared renderer draws fallback tiles from these semantic tokens.",
    },
  ],
  tilesets: [
    {
      id: TILESET_ID,
      sourceId: SOURCE_ID,
      tileWidth: TILE_SIZE,
      tileHeight: TILE_SIZE,
      columns: 8,
      atlasImagePath: "apps/rpg-idle-demo/public/assets/rpg-idle-atlas.svg",
      manifestPath: "apps/rpg-idle-demo/public/assets/rpg-idle-atlas.manifest.json",
      exportScale: 1,
    },
  ],
  tokens: [
    token("floor.grass_meadow", "floor", "floor", 8, 1, 1, false, [
      "rpg",
      "terrain",
      "grass",
    ]),
    token("wall.stone.straight", "wall", "wall", 24, 1, 1, true, [
      "rpg",
      "boundary",
      "stone",
    ]),
    token("wall.stone.corner", "wall", "wall", 25, 1, 1, true, [
      "rpg",
      "boundary",
      "stone",
      "corner",
    ]),
    token("item.resource_node.tree", "item", "object", 64, 1, 1, true, [
      "rpg",
      "resource",
      "tree",
    ], {
      collisionFootprint: { x: 7, y: 15, width: 18, height: 15 },
      visualFootprint: { x: 3, y: 1, width: 26, height: 30 },
      shadowFootprint: { x: 6, y: 24, width: 20, height: 6 },
      zAnchor: { x: 16, y: 30 },
      interaction: {
        affordance: "gather",
        label: "Ancient tree",
        prompt: "Gather wood",
        radiusTiles: 1.4,
        priority: 40,
      },
      themeTags: ["woodland", "resource"],
      occlusionMode: "y_sort",
    }),
    token("item.building_site.cabin", "item", "object", 72, 2, 2, true, [
      "rpg",
      "building",
      "site",
    ], {
      collisionFootprint: { x: 5, y: 18, width: 54, height: 42 },
      visualFootprint: { x: 0, y: 2, width: 64, height: 60 },
      shadowFootprint: { x: 5, y: 54, width: 54, height: 8 },
      zAnchor: { x: 32, y: 60 },
      interaction: {
        affordance: "inspect",
        label: "Outpost site",
        prompt: "Inspect site",
        radiusTiles: 1.2,
        priority: 20,
      },
      themeTags: ["woodland", "building"],
      occlusionMode: "y_sort",
    }),
  ],
  styles: [
    {
      id: "style.grove_outpost",
      floorTokenId: "floor.grass_meadow",
      wallTokenIds: {
        straight: "wall.stone.straight",
        corner: "wall.stone.corner",
      },
      tags: ["rpg", "outpost", "woodland"],
    },
  ],
}

export const RPG_IDLE_DEMO_ENTITIES: readonly RpgIdleEntity[] = [
  {
    id: "hero.scout",
    kind: "hero_unit",
    label: "Scout",
    spawnPointId: "hero_spawn",
  },
  {
    id: "resource.ancient_tree",
    kind: "resource_node",
    label: "Ancient tree",
    tokenId: "item.resource_node.tree",
    tile: { x: 3, y: 3 },
    interactionZoneId: "zone.grove",
  },
  {
    id: "building.outpost_site",
    kind: "building_site",
    label: "Outpost site",
    tokenId: "item.building_site.cabin",
    tile: { x: 8, y: 5 },
  },
]

export const RPG_IDLE_DEMO_ACTIONS: readonly RpgIdleAction[] = [
  {
    id: "gather_wood",
    label: "Gather wood",
    targetEntityId: "resource.ancient_tree",
    requiredZoneId: "zone.grove",
    resourceDelta: {
      wood: 1,
    },
  },
]

export function createRpgIdleDemoMap(): RpgIdleDemoMap {
  const definition = rpgIdleDemoDefinition()
  const compiled = compileSemanticMapDefinition(definition, RPG_IDLE_DEMO_CATALOG)
  const spawnPoints = [
    tileSpawnPoint("hero_spawn", { x: 4, y: 4 }, compiled.tileSize),
  ]
  const validation = validateCompiledMap(compiled, spawnPoints)

  return {
    id: "rpg_idle_grove",
    label: "Grove Outpost",
    definition,
    compiled,
    spawnPoints,
    validation,
  }
}

export function rpgIdleDemoDefinition(): SemanticMapDefinition {
  return {
    roomDimensions: { width: 12, height: 9 },
    style: "style.grove_outpost",
    layers: {
      walls: boundaryWalls(12, 9),
      objects: [
        { x: 3, y: 3, tokenId: "item.resource_node.tree" },
        { x: 8, y: 5, tokenId: "item.building_site.cabin" },
      ],
      zones: [
        {
          id: "zone.grove",
          xStart: 2,
          yStart: 2,
          xEnd: 6,
          yEnd: 6,
          zoneType: "resource.gathering",
        },
      ],
    },
  }
}

export function referencedRpgTokens(
  compiled: CompiledSemanticMap,
): readonly VisualTokenDefinition[] {
  const referencedTokenIds = new Set(compiled.referencedTokenIds)
  return RPG_IDLE_DEMO_CATALOG.tokens.filter((token) =>
    referencedTokenIds.has(token.id),
  )
}

function boundaryWalls(
  width: number,
  height: number,
): SemanticMapDefinition["layers"]["walls"] {
  const walls: SemanticWallPlacement[] = []

  for (let x = 0; x < width; x += 1) {
    walls.push({ x, y: 0, type: isHorizontalCorner(x, width) ? "corner" : "straight" })
    walls.push({
      x,
      y: height - 1,
      type: isHorizontalCorner(x, width) ? "corner" : "straight",
    })
  }

  for (let y = 1; y < height - 1; y += 1) {
    walls.push({ x: 0, y, type: "straight" })
    walls.push({ x: width - 1, y, type: "straight" })
  }

  return walls
}

function isHorizontalCorner(x: number, width: number): boolean {
  return x === 0 || x === width - 1
}

function token(
  id: string,
  kind: VisualTokenDefinition["kind"],
  layer: VisualTokenDefinition["layer"],
  provisionalGid: number,
  widthTiles: number,
  heightTiles: number,
  collidable: boolean,
  tags: readonly string[],
  options: FrameOptions = {},
): VisualTokenDefinition {
  return {
    id,
    kind,
    layer,
    sourceId: SOURCE_ID,
    tilesetId: TILESET_ID,
    provisionalGid,
    widthTiles,
    heightTiles,
    collidable,
    asset: frame(id, widthTiles, heightTiles, collidable, options),
    tags,
  }
}

function frame(
  frameId: string,
  widthTiles: number,
  heightTiles: number,
  collidable: boolean,
  options: FrameOptions,
): VisualAssetFrameMetadata {
  const width = widthTiles * TILE_SIZE
  const height = heightTiles * TILE_SIZE

  return {
    atlasId: ATLAS_ID,
    frameId,
    size: {
      width,
      height,
      exportScale: 1,
    },
    anchor: {
      x: width / 2,
      y: height / 2,
    },
    collisionFootprint:
      options.collisionFootprint ??
      (collidable
        ? { x: 0, y: 0, width, height }
        : { x: 0, y: 0, width: 0, height: 0 }),
    visualFootprint: options.visualFootprint ?? { x: 0, y: 0, width, height },
    shadowFootprint:
      options.shadowFootprint ??
      (frameId.startsWith("floor.")
        ? { x: 0, y: 0, width: 0, height: 0 }
        : {
            x: Math.round(width * 0.16),
            y: Math.max(0, height - 7),
            width: Math.round(width * 0.68),
            height: 5,
          }),
    zAnchor: options.zAnchor ?? { x: width / 2, y: height },
    interaction: options.interaction ?? { affordance: "none" },
    occlusion: {
      mode: options.occlusionMode ?? "none",
    },
    themeTags: options.themeTags ?? ["rpg", "procedural"],
    variants: [
      {
        id: `${frameId}.default`,
        label: "Default",
        role: "default",
        frameId,
        themeTags: options.themeTags ?? ["rpg", "procedural"],
      },
    ],
  }
}
